### ISSUE TITLE
Poor performance when writing to Azure storage

### ISSUE THREAD

**Issue by RoelofSpijker** [aloneguid/parquet-dotnet#183] opened 2022-09-30 14:33 UTC
**Version:** Parquet.Net v3.9.1

**Runtime Version:** .Net Framework v4.8

**OS:** Windows

#### Expected behavior
Expected ability to write to Azure storage via a stream relatively fast.

#### Actual behavior
Actual performance is very poor. It takes 20 minutes longer to write an 80MB file using the streaming version compared to writing to a local file and then sending that file to Azure storage.

### Steps to reproduce the behavior

1. Generate many records (say 1M with 10 columns per record)
2. Open a stream to Azure storage (although, I imagine any network stream will have the same issue)
3. Create a RowGroup per 5_000 rows (as advised) and write each of the columns to the file. Loop over all records in this way.

Some investigation shows that `ParquetRowGroupWriter.WriteColumn` flushes the underlying stream twice. During the process of writing the headers in `ThriftStream.Write`. This means flush is called on the stream pointing to a file on Azure Storage twice for every `WriteColumn` invocation. For 1M records, grouping them per 5K that's 200 groups. For each group we call `WriteColumn` 10 times (once per column) so we get 2000 `WriteColumn` invocation and thus 4000 Flushes. That is a *significant* amount of network overhead.

I imagine this is a fairly common usecase, given what Parquet is mostly used for. I would like to avoid creating a local file or drastically increasing the size of my rowGroups. Is there a good reason to flush twice on each `WriteColumn` invocation?

#### Code snippet reproducing the behavior

This example emulates writing over a network by wrapping the stream and adding a configurable delay upon flushing.

```csharp
public async Task Test()
{
    var ids = Enumerable.Range(1, 100_000).ToArray();
    var idField = new DataField<int>("id");
    var nums1 = Enumerable.Range(1, 100_000).Select(x => x.ToString()).ToArray();
    var num1Field = new DataField<string>("num1");
    var nums2 = Enumerable.Range(1, 100_000).Select(x => x.ToString()).ToArray();
    var num2Field = new DataField<string>("num2");
    // create file schema
    var schema = new Schema(idField, num1Field, num2Field);

    void WriteFile(int delay)
    {
        using (Stream stream = new NetworkStreamEmulator(File.OpenWrite($"{Guid.NewGuid()}.parquet"), delay)) // 100ms delay on each flush
        {
            using (var parquetWriter = new ParquetWriter(schema, stream))
            {
                for (var i = 0; i < 100_000; i += 5000) // 20 groups, 3 columns, 2 flushes per column = 120 flushes = 12s overhead 
                {
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        groupWriter.WriteColumn(new DataColumn(idField, ids.Skip(i).Take(5_000).ToArray()));
                        groupWriter.WriteColumn(new DataColumn(num1Field, nums1.Skip(i).Take(5_000).ToArray()));
                        groupWriter.WriteColumn(new DataColumn(num2Field, nums2.Skip(i).Take(5_000).ToArray()));
                    }
                }
            }
        }
    }

    var sw = new Stopwatch();
    sw.Start();
    WriteFile(100);
    Console.WriteLine($"Took {sw.ElapsedMilliseconds}ms with 100ms delay");
    sw.Restart();
    WriteFile(0);
    Console.WriteLine($"Took {sw.ElapsedMilliseconds}ms with 0ms delay");
}

private class NetworkStreamEmulator : Stream
{
    private readonly Stream _wrapped;
    private readonly int _emulatedDelayMs;
    
    public NetworkStreamEmulator(Stream wrapped, int emulatedDelayMs = 200)
    {
        _wrapped = wrapped;
        _emulatedDelayMs = emulatedDelayMs;
    }
    
    public override void Flush()
    {
        Thread.Sleep(_emulatedDelayMs);
        _wrapped.Flush();
    }
    // Otherwise just wraps the Stream it is passed
}
```

This results in:

```
Took 13095ms with 100ms delay
Took 62ms with 0ms delay
```

**Comment by aloneguid** [comment] 2022-10-13 09:19
For these situations .NET has built-in [BufferedStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.bufferedstream?view=net-7.0) class.

**Comment by RoelofSpijker** [comment] 2022-10-14 07:52
I'm unsure how this would help. Perhaps I misunderstand your suggestion, but I believe wrapping the stream in a BufferedStream will not help. The streams I'm using in my actual code already use buffers internally. Perhaps my example simplified things a little bit too much and the core of the issue was lost. The underlying issue is that `WriteColumn` *flushes* twice. `BufferedStream` will buffer reads and writes, but it will propagate flushes to the underlying stream if there is _anything_ in the respective read or write buffers.

The example (and real) code still shows the same difference in performance when using a BufferedStream, as the frequency of flushes makes it so that the data in the buffer when a flush occurs will usually be relatively small.

Perhaps this is a product of me adhering too strictly to the advised row group size. After some research it seems that the [Parquet format](https://parquet.apache.org/docs/file-format/configurations/#row-group-size) generally advises about row group sizes in terms of bytes rather than number of rows. In my case I can increase the row group size quite drastically to avoid the excessive costs associated with the flushes. However, this issue would still present itself in cases where the amount of columns is far greater as the amount of flushes scales linear with that.

I was not able to deduce the necessity of flushing twice upon each `WriteColumn` call. I'm sure there's a reason for it, could you perhaps explain?

**Comment by aloneguid** [comment] 2022-10-14 10:21
Hi. Generally there should be no reason to flush twice. You might want to try the latest version as it has some good improvements.
Generally performance will be going up in v4 due to dropping .net standard 2.0 which opens some wide doors.

**Comment by RoelofSpijker** [comment] 2022-10-14 12:29
I tried v4, it still has the same issue. This was before you introduced the IronCompress changes, which do change the code path slightly, but does not affect the flushing behaviour.

Specifically, [`ParquetGroupWriter.WriteColumnAsync`](https://github.com/aloneguid/parquet-dotnet/blob/67173d7534240f65fb4ced0372d8ef6bc4459a2b/src/Parquet/ParquetRowGroupWriter.cs#L79) calls [`DataColumnWriter.WriteColumnAsync`](https://github.com/aloneguid/parquet-dotnet/blob/67173d7534240f65fb4ced0372d8ef6bc4459a2b/src/Parquet/File/DataColumnWriter.cs#L124) which calls [`ThriftStream.WriteAsync`](https://github.com/aloneguid/parquet-dotnet/blob/67173d7534240f65fb4ced0372d8ef6bc4459a2b/src/Parquet/File/ThriftStream.cs#L41) which flushes the `ThriftStream` twice, but as that wraps the actual content stream, that also gets flushed twice.

**Comment by aloneguid** [comment] 2023-02-15 10:20
I've decided not to do it. By design Parquet format is not streamable. Best way to go around is to write to file or memory stream, then upload elsewhere. If we start thinking about Azure or other providers this will quickly get out of scope.

**Closed by aloneguid** 2023-02-15 10:20 UTC
