### ISSUE TITLE
Arbitrary serialization has vanished

### ISSUE THREAD

**Issue by masonwheeler** [aloneguid/parquet-dotnet#402] opened 2023-09-21 02:59 UTC
### Library Version

4.16.4

### OS

All

### OS Architecture

64 bit

### How to reproduce?

I just updated Parquet.Net to the latest version and have dozens of breaking changes throughout my project.

The `Parquet.Data.Rows` namespace is missing entirely.  The `DataType` enum is gone.  Classes like `Table`, `Schema`, and `DataField` are gone.  It looks like all of the code I was using for serialization of arbitrary data has vanished into the ether.

Well, ***I was using that code!***  The documentation says that the preferred method is to serialize objects with class-based serializers, which is all well and good if you have your data in objects in the first place, but I didn't.  I was using Parquet.Net specifically because *I don't have data objects.*  I have `IDataReader`s containing database query results.  They can be arbitrary queries, whose schema is not known at compile time, and I need to serialize them, and Parquet.Net was the only library I found that did anything resembling a good job at that.

And now all that code I was using is gone.  Please tell me it's been replaced by something better, and not simply rug-pulled out from under me!

What is the preferred method for serializing arbitrary data, now that the old code for it is gone?

**Comment by aloneguid** [comment] 2023-09-21 06:26
You have probably upgraded major versions :) it's all there, just moved namespaces.

There's documentation website and unit tests showing how to use it.

**Comment by aloneguid** [comment] 2023-09-25 09:39
feel free to ask more questions, closing as not a bug

**Closed by aloneguid** 2023-09-25 09:39 UTC
