### ISSUE TITLE
[BUG]: Fail to serialize enum

### ISSUE THREAD

**Issue by pantonis** [aloneguid/parquet-dotnet#442] opened 2023-12-21 09:02 UTC
### Library Version

4.17.0

### OS

Windows 10

### OS Architecture

64 bit

### How to reproduce?

For some reason it seems that enum fail to be serialized.

````
 internal class ParquetEnumTest
 {
     internal async Task ClientTest()
     {
         List<Client> clients = new();
         for (int i = 0; i < 10; i++)
         {
             clients.Add(new Client
             {
                 Id = i,
                 Name = $"Client {i}",
                 ClientStatus = (ClientStatus)(i % 4 + 1)
             });
         }

         using (var memStream = new MemoryStream())
         {
             await ParquetSerializer.SerializeAsync(clients , memStream);
             memStream.Seek(0, SeekOrigin.Begin);

             var parquetBytes = memStream.ToArray();
         }
     }
 }

 internal class Client
 {
     public int Id { get; set; }
     public string Name { get; set; }
     public ClientStatus ClientStatus { get; set; }
 }

 public enum ClientStatus
 {
     Active = 1,
     Inactive = 2,
     Blocked = 3,
     Archived = 4
 }

````

and Im getting the following exception

```
property 'ClientStatus' has no fields

   at Parquet.Serialization.TypeExtensions.MakeField(Type t, String columnName, String propertyName, PropertyInfo pi, Boolean forWriting)
   at Parquet.Serialization.TypeExtensions.MakeField(PropertyInfo pi, Boolean forWriting)
   at Parquet.Serialization.TypeExtensions.<>c__DisplayClass13_0.<CreateSchema>b__0(PropertyInfo p)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at Parquet.Serialization.TypeExtensions.CreateSchema(Type t, Boolean forWriting)
   at Parquet.Serialization.TypeExtensions.GetParquetSchema(Type t, Boolean forWriting)
   at Parquet.Serialization.ParquetSerializer.<>c__3`1.<SerializeAsync>b__3_0(Type _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Parquet.Serialization.ParquetSerializer.<SerializeAsync>d__3`1.MoveNext()
```

**Comment by aloneguid** [comment] 2023-12-21 09:22
Enums are not supported yet, see #302 as this is in progress. As you are working with enums, can I ask how you are expecting it to be written, as a number, as a string etc.?

**Comment by pantonis** [comment] 2023-12-21 10:00
thanks for the clarification. Expect it to as fast as possible (number)

**Comment by aloneguid** [comment] 2024-01-17 22:25
Thank you. Closing as duplicate of #302 for now.

**Closed by aloneguid** 2024-01-17 22:25 UTC
Labels: duplicate
